# Generated by Django 4.2.1 on 2023-06-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.categories'),
            preserve_default=False,
        ),
    ]
